version: "3.3"
services:
  app:
    build:
      context: "./api"
    # env_file: .env
    restart: unless-stopped
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_MAX_OPEN_CONNS: "20"
      MYSQL_MAX_IDLE_CONNS: "20"
      REMOTE_STORAGE_ENDPOINT: "minio:9000"
      # REMOTE_STORAGE_ENDPOINT: "127.0.0.1:9000"

      REMOTE_STORAGE_ACCESS_KEY_ID: "minioadmin"
      REMOTE_STORAGE_ACCESS_KEY_SECRET: "minioadmin"
      REMOTE_STORAGE_USE_SSL: "false"
    volumes:
      - ./api/:/app/
    depends_on:
      - mysql
      - minio
    links:
      - mysql
      - minio
    ports:
      - "8080:8080"
  mysql:
    image: "mariadb:10.3"
    stop_signal: SIGKILL
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    restart: always
    # environment:
    #   # MYSQL_USER: "user"
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: exercise
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
  minio:
    image: minio/minio
    command: "server /data"
    volumes:
      - ./var/minio:/data
    ports:
      - 9000:9000