# build stage
FROM golang:1.14-buster as builder

WORKDIR /app

COPY api /app

RUN go mod download
# RUN install -v -mod=vendor ./cmd/...

RUN go build -o /main ./cmd

# Run stage
FROM debian:buster

RUN apt-get update --fix-missing && \
apt-get install -yqq ca-certificates

COPY --from=builder /main .

COPY --from=builder /app/ui .

CMD ["/main"]