version: "3.3"
services:
  app:
    build:
      context: "../../"
      dockerfile: docker/local/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./testfiles/:/testfiles/
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
      - minio
    ports:
      - "80:80"

  mysql:
    image: "mariadb:10.3"
    stop_signal: SIGKILL
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: mysql --user=user --password=password --execute="SELECT healthy FROM photoshare.healthcheck" --host=mysql --port=3306 --skip-column-names --silent | grep OK
      interval: "1s"
      retries: 60
      timeout: "500ms"
    restart: always
    volumes:
      - ./db/dbinit:/docker-entrypoint-initdb.d:ro
    # ports:
    #   - "3308:3306"

  minio:
    image: minio/minio
    command: "server /data"
    volumes:
      - ./var/minio:/data
    ports:
      - 9000:9000
