# build stage
FROM golang:1.14-buster as builder

WORKDIR /app

COPY . .

RUN go mod download
# RUN install -v -mod=vendor ./cmd/...

RUN go build -o main ./cmd

# Run stage
FROM debian:buster

RUN apt-get update --fix-missing && \
apt-get install -yqq ca-certificates

COPY --from=builder /app .

# Copy the Pre-built binary file from the previous stage
# COPY --from=builder /app/main .

# RUN chmod +x ./main

# final stage
# FROM scratch
# COPY --from=builder /app/main /app/
EXPOSE 8080
CMD ["./main"]